export const CONFIG = {
  SITE_PROTOCOL: "SITE_PROTOCOL",
  SITE_DOMAIN: "SITE_DOMAIN",
  SITE_SERVER_PORT: "SITE_SERVER_PORT",
  SITE_CLIENT_PORT: "SITE_CLIENT_PORT",
  DB_CONNECTION: "DB_CONNECTION",
};
